#!/usr/bin/env bash
set -e

declare -a VIDEOS
cd /srv/http/tmcassets/video/

while read f; do
    NAME1=${f##./}
    NAME2=${NAME1%%.*}
    VIDEOS+=(${NAME2})
done < <(find . -maxdepth 1 -type f)

printf '%s\n' "${VIDEOS[@]}" | sort | uniq
