#!/usr/bin/env bash

declare -a VIDEOS
WORK_DIR=$(pwd)
cd /srv/http/tmcassets/video/

containsElement () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

appendElement () {
    VIDEOS+=(${1})
}

FILES=$(find . -maxdepth 1 -type f)

while read f; do
    NAME1=${f##./}
    NAME2=${NAME1%%.*}
    if ! containsElement ${NAME2} VIDEOS; then
        VIDEOS+=${NAME2}
    fi
done < <(find . -maxdepth 1 -type f)

for vid in ${VIDEOS}; do
    echo "${vid}"
done