#!/usr/bin/env bash

WORK_DIR=$(pwd)
DELIM="|"

cd /srv/http/tmcassets/video/

if [ -t 0 ]; then
    if [[ $# -ne 1 ]]
    then
        echo "Usage: ./listvideofiles videoname"
        echo "Do not include extention"
        echo "Gather and output all the info about each file associated with a video name"
        exit 1
    fi

    FILES=$(find . -maxdepth 1 -type f -name "${1}*")

    for FILE in ${FILES}; do
    declare -a FILEINFO
    FILEINFO=$(${WORK_DIR}/videofileinfo "${FILE}")
    FILESIZE=$(stat -c%s "${FILE}")
    echo "${FILEINFO}${DELIM}${FILESIZE}"
done

else
    while read -r line ; do
        FILES=$(find . -maxdepth 1 -type f -name "${line}*")
        for FILE in ${FILES}; do
            declare -a FILEINFO
            FILEINFO=$(${WORK_DIR}/videofileinfo "${FILE}")
            FILESIZE=$(stat -c%s "${FILE}")
            echo "${FILEINFO}${DELIM}${FILESIZE}"
        done
    done
fi


